models/urls.py
from django.contrib import admin
from django.urls import path, include
# from myapp import views
import myapp


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myapp.urls")),
    
]

myapp/urls.py
from django.urls import path
from myapp import views
app_name = 'myapp'

urlpatterns = [
    
    path('',views.index, name='index'),
    path('display/',views.display, name='display'), # display all data 
    path('display-asc/',views.display_asc, name='display_asc'), # display all data in asc order
    path('display-specific/',views.display_specific, name='display_specific'),
    path('filter-data/',views.filter_data, name='filter_data'),
    path('like-data/',views.like_data, name='like_data'),

    # display topic details by submitting single topic by select option
    path('form/',views.topic_form, name='topic_form'),
    path('web-details/',views.web_details, name='web_details'),

    # display topic details by submitting multiple topic by checkbox
    path('form2/',views.topic_form2, name='topic_form2'),
    path('web-details2/',views.web_details2, name='web_details2'),

    # insert topic by form 
    path('create-topic/',views.create_topic, name='create_topic'),
    

    # insert webpage by form with foreign key 
    path('create-webpage/',views.create_webpage, name='create_webpage'),

    # select webpage for update by dropdown  
    path('select-webpage/',views.select_webpage, name='select_webpage'),

    # edit webpage details for update in form  
    path('edit-webpage/',views.edit_webpage, name='edit_webpage'),

    # edit webpage details for update in form  
    path('update-webpage/',views.update_webpage, name='update_webpage'),

    # insert access details by form with foreign key 
    path('create-access-details/',views.create_access_details, name='create_access_details'),

    # delete topic by form 
    path('delete-topic/',views.delete_topic, name='delete_topic'),






    
]

myapp/models.py
from django.db import models
from myapp.models import *

# Create your models here.


class Topic(models.Model):
    top_name = models.CharField(max_length=120, primary_key=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    top_name = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, primary_key=True)
    url = models.URLField(unique=True)

    def __str__(self):   
        return self.name 

class Access_Details(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField(unique=True)

    def __str__(self):
        return str(self.date)
    
    
    

myapp/views.py
from django.shortcuts import render
from myapp.models import *
from django.http import HttpResponse,HttpResponseRedirect


# Create your views here.

def index(request):
    return render(request, "index.html")

# Display all()
def display(request):
    data_topic = Topic.objects.all() # Topic is the Class name / Table name
    data_webpage = Webpage.objects.all() # Webpage is the Class name / Webpage name
    data_access_details = Access_Details.objects.all() # Access_Details is the Class name / Webpage name

    top = {'topics':data_topic, 'webpages':data_webpage, 'access_details':data_access_details}
    return render(request, "display.html", context=top)


# Display ascending order
def display_asc(request):
    access_details_asc = Access_Details.objects.order_by('date') # order_by() ordered all the data by asc order
    access_date = {'dates':access_details_asc}
    return render(request, "display_asc.html", context=access_date)


# Display a specific record # using get(key:value)
def display_specific(request):
    # specific = Webpage.objects.get('name')    
    # specific_name = {'names':specific}    
    return render(request, "display_specific.html")  



# Display the filter data
def filter_data(request):
    filterdata = Webpage.objects.filter(top_name = "Music")
    return render(request, "filter_data.html", context={'webpage':filterdata}) 

#startswith , endswith, and contains check 
def like_data(request):
    return render(request, "like_data.html")


# form demo where accepts the topic and display the topic details in webpage_details page

def topic_form(request):
    topics = Topic.objects.all()
    if request.method == "POST":
        topic = request.POST.get("top")  # getlist is for displaying multiple dropdown data
        # topic = request.POST.getlist("top")
        web_data = Webpage.objects.filter(top_name = topic)
        return render(request, "webpage_details.html", context={"webpages":web_data})
    return render(request, "form_demo.html", context={"topics":topics})

# def topic_form(request):
#     topics = Topic.objects.all()
#     if request.method == "POST":
#         # topic = request.POST.get("top")
#         topic = request.POST.getlist("top") # getlist is for displaying multiple dropdown data
#         webpages = Webpage.objects.none()
#         for i in topic:
#             webpages = webpages | Webpage.objects.filter(top_name=i)
#         return render(request, "webpage_details.html", context={"webpages":webpages})
#     return render(request, "form_demo.html", context={"topics":topics})



#it displays the webpage details by selecting from dropdown
def web_details(request):
    webpages = Webpage.objects.all()
    return render(request, "webpage_details.html", context={"webpages":webpages})


# form demo where accepts the topic and display the topic details in webpage_details page
def topic_form2(request):
    topics = Topic.objects.all()
    if request.method == "POST":
        # topic = request.POST.get("top")
        topic = request.POST.getlist("top") # getlist is for displaying multiple dropdown data
        webpages = Webpage.objects.none()
        for i in topic:
            webpages = webpages | Webpage.objects.filter(top_name=i)
        return render(request, "webpage_details2.html", context={"webpages":webpages})
    return render(request, "form_demo2.html", context={"topics":topics})



#it displays the webpage details by selecting from dropdown
def web_details2(request):
    webpages = Webpage.objects.all()
    return render(request, "webpage_details2.html", context={"webpages":webpages})


# it insert topics into the database by using form
def create_topic(request):
    if request.method == "POST":
        top_name = request.POST.get("top")  # this "top" is the name="top" from create_form
        t = Topic.objects.get_or_create(top_name = top_name)[0]
        t.save()
    return render(request, "create_topic.html")



# it will insert webpage by using form with foreign key reference , with the help of topic dropdown 
def create_webpage(request):
    if request.method == "POST":
        top_name = request.POST.get("top")
        t=Topic.objects.get_or_create(top_name = top_name)[0]
        t.save()
        name = request.POST.get("name")
        url = request.POST.get("url")
        w = Webpage.objects.get_or_create(top_name = t, name = name, url = url)[0]
        w.save()
    topics = Topic.objects.all()
    return render(request,"create_webpage.html", context={"topics":topics})

# update 
def select_webpage(request):
    webpages = Webpage.objects.all()
    return render(request, "select_webpage_for_update.html", context={"webpages":webpages})
        
def edit_webpage(request):
    if request.method=="POST":
        name=request.POST.get("name")
        webpage=Webpage.objects.get(name=name)
        return render(request,"edit_webpage.html",context={"webpage":webpage})
    return HttpResponse("No Data Found, <br> First Select the Webpage name.<br>\
     To select webpage name Click <a href='http://localhost:8000/select-webpage'>Here</a>")


def update_webpage(request):
    if request.method=="POST":
        top_name=request.POST.get("top")
        name=request.POST.get("name")
        url=request.POST.get("url")
        t=Topic.objects.get_or_create(top_name=top_name)[0]
        web=Webpage.objects.filter(name=name).update(top_name=t,url=url)
        t.save()
        
    return HttpResponse("<h3>Record Updated successfully</h3>")

def create_access_details(request):
    if request.method == "POST":
        name = request.POST.get("name") # form element name="name"
        w = Webpage.objects.get_or_create(name = name)[0] # name = field name
        w.save()
        date = request.POST.get("date")
        a = Access_Details.objects.get_or_create(name = w, date = date)[0]
        a.save()
    access_details = Access_Details.objects.all()
    return render(request, "create_access_details.html", context={"access_details" : access_details})



# This fumction deletes only Topic 
def delete_topic(request):
    topics = Topic.objects.all()
    if request.method == "POST":
        data = request.POST.getlist("top")
        for i in data:
            t = Topic.objects.get(top_name = i)
            t.delete()
            t.save()
        
    return render(request, "delete_topic.html", context={"topics":topics})




# This function deletes Topics as well as its reference table data ..

# Write the code here for it , take help from akshay sir note book 


# def delete_topic(request):
#     topics = Topic.objects.all()
#     if request.method == "POST":
#         data = request.POST.get("top")
#         t = Webpage.objects.filter(top_name = data)
#         t.delete()
#         t.save()
        
#         # print(topics)
#     return render(request, "delete_topic.html", context={"topics":topics})

myapp/templates/create_access_details.html
{% extends "index.html" %}

{% block title %}
    <title> Add Access Details</title>
{% endblock %}


{% block body_block %}
<div class="container">
    <div class="jumbotron">      
    <h5 align="center">
        If you want to create Access Details then fillup the form proper way.
    </h5>
    </div>
    <h1>Enter the Details to create Access Details</h1> <br>
    <table>
    <form method="POST">
        {% csrf_token %}
        {% if access_details %}
        <tr> <td>Choose Webpage Name :<select name="name" id="name">
            {% for access_detail in access_details %}
            <option value="{{access_detail}}">{{access_detail.name}}</option>
            {% endfor %}
        </select> </td></tr><br>
        {% endif %}
        <tr><td>Access Date: <input type="date" name="date" id="date"><br>
        <tr><td><input class="btn btn-primary" type="submit" value="Submit"></td></tr>
        
    </form>
</table>

    </div>
{% endblock body_block %}

myapp/templates/create_topic.html
{% extends "index.html" %}

{% block title %}
    <title> Add Topic</title>
{% endblock %}


{% block body_block %}
<div class="container">
    <div class="jumbotron">      
    <h5 align="center">
        If you want to create Topic then fillup the form with a topic name.
    </h5> 
    </div>
    
    <h1 align="center"> Create Topic Here</h1><br>
        <form method="POST" align="center">
            {% csrf_token %}            
           <b>Topic</b> : <input type="text" name="top" id="top" placeholder="Enter Topic name">
           <input class="btn btn-primary" type="submit" value="Submit">
        </form>

    </div>
{% endblock body_block %}

myapp/templates/create_webpage.html
{% extends "index.html" %}

{% block title %}
    <title> Add Webpage</title>
{% endblock %}


{% block body_block %}
<div class="container">
    <div class="jumbotron">      
    <h5 align="center">
        If you want to create webpage then fillup the form proper way.
    </h5>
    </div>
    <h1>Enter the Details to create Webpage</h1> <br>
    <table>
    <form method="POST">
        {% csrf_token %}
        {% if topics %}
        <tr> <td>Choose Topic :<select name="top" id="top">
            {% for topic in topics %}
            <option value="{{topic}}">{{topic.top_name}}</option>
            {% endfor %}
        </select> </td></tr><br>
        {% endif %}
        <tr><td>Webpage Name: <input type="text" name="name" id="name"><br>
        <tr><td> Webpage Url : <input type="url" name="url" id="url"><br></td></tr>
        <tr><td><input class="btn btn-primary" type="submit" value="Submit"></td></tr>
        
    </form>
</table>

    </div>
{% endblock body_block %}

myapp/templates/delete_topic.html
{% extends "index.html" %}

{% block title %}
    <title> Check topic</title>
{% endblock %}


{% block body_block %}
<div class="container">
    <div class="jumbotron">      
    <h5 align="center">
        Check a topic name you want to delete  <br>
        If you want you can coose multiple topic for delete.
    </h5> 
    </div>
    <h1 align="center">Choose the Topic for Delete</h1>
    <table align="center">
    {% if topics %}
    <form method="POST">
        {% csrf_token %}
        {% for topic in topics  %}
          
       <tr> 
        <td><label for="top">{{topic.top_name}}</label></td>
        <td><input type="checkbox" name="top" id="top" value="{{topic}}"></td> 
      </tr>
       {% endfor %}

    <tr> </tr></tr>
    <tr><td><input class="btn btn-danger" type="submit" value="Delete"></td> </tr></tr>
</form>
</table>
{% else %}
    <h1>Data not found</h1>
{% endif %}
</div>
<br>
<br>
{% endblock body_block %}

myapp/templates/display.html
{% extends "index.html" %}

{% block title %}
    <title> Display All</title>
{% endblock %}

{% block body_block %}
<div class="container">
  <div class="jumbotron">      
  <h5 align="center">
      All the table data present here all are coming from database.
      Which are stored in different tables and these are DISPLAYED here in the same table name.
  </h5>
  </div>
  </div>

    <!-- Topic table  -->
<div class="container">
  <div class="row">
      {% if topics %}
      <strong><h4>Webpage Topic Details</h4></strong>
      <table class="table align-center">
          <thead class="thead-dark">
          <tr>
              <!-- <th scope="col"></th> --> 
              <th scope="col">Webpage Topic Name</th>        
          </tr>
          </thead>
          <tbody>
              {% for topic in topics %}
          <tr>
              <!-- <th scope="row"></th> -->
              <td>{{topic.top_name}}</td>        
          </tr>
          {% endfor %}
          </tbody>
      </table>
    {% else %}
          <h1>No Data Found</h1>
  {% endif %}
  
  </div>
  </div>
  <!-- web page table  -->
     
  <div class="container">
      {% if webpages %}
      <strong><h4>Webpage Deatails</h4></strong>
      <table class="table">
          <thead class="thead-dark">
            <tr>
                  <th scope="col">Webpage Topic</th>        
                  <th scope="col">Webpage Name</th>        
                  <th scope="col">URL</th>   
            </tr>
          </thead>
          <tbody>
              {% for webpage in webpages %}
            <tr>
              <td>{{webpage.top_name}}</td>        
              <td>{{webpage.name}}</td>        
              <td>{{webpage.url}}</td> 
            </tr>
            {% endfor %}
            
          </tbody>
      </table>
      {% else %}
      <thead class="thead-dark">
          <tr>
                <th scope="col">Webpage Topic</th>        
                <th scope="col">Webpage Name</th>        
                <th scope="col">URL</th>   
          </tr>
        </thead>
          <h1>No Data Found</h1>
      {% endif %} 
  </div>
  
  
      <!-- Access Details Table  -->
  
  <div class="container">
      {% if access_details %}
      <strong><h4>Access Deatails</h4></strong>
      <table class="table">
          <thead class="thead-dark">
            <tr>
                  <th scope="col">Webpage Name</th>        
                  <th scope="col">Access Date</th>        
            </tr>
          </thead>
          <tbody>
              {% for access_detail in access_details %}
            <tr>
              <td>{{access_detail.name}}</td>        
              <td>{{access_detail.date}}</td>        
            </tr>
            {% endfor %}
            
          </tbody>
      </table>
      {% else %}
      <thead class="thead-dark">
          <tr>
              <th scope="col"> Webpage Name </th>        
              <th scope="col">Access Date</th>
          </tr>
        </thead>
          <h1>No Data Found</h1>
      {% endif %} 
  </div>
  
  
{% endblock body_block %}

myapp/templates/display_asc.html
{% extends "index.html" %}

{% block title %}
    <title> Display Asc </title>
{% endblock %}

{% block body_block %}
<div class="container">
  <div class="jumbotron">      
  <h5 align="center">
      All the table data present here all are coming from database. And organised into ASCENDING order
  </h5>
  </div>

  {% if dates %}
  <h4>Access Dates in Ascending Order</h4>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <!-- <th scope="col">Webpage Name</th> -->
                <th scope="col">Webpage Name</th>
                <th scope="col">Access Date</th>
            </tr>
        </thead>
        <tbody>
            {% for date in dates  %}
            <tr>
                <td>{{ date.name}}</td>
                <td>{{ date.date}}</td>
            </tr>
              
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h1>
        no data found
    </h1>
    
  {% endif %}
  </div>
  {% endblock body_block %}

myapp/templates/edit_webpage.html
{% extends "index.html" %}

{% block title %}
    <title> Edit Webpage</title>
{% endblock %}


{% block body_block %}
<div class="container">
    <div class="jumbotron">      
    <h2 align="center">
        Edit WebPage for update <br>
    </h2> 
    </div>
    <h1>Edit The fields and click on submit</h1>
    

    <form action="{% url 'myapp:update_webpage' %}"  method="POST">
        {% csrf_token %}
        top_name: <input type="text" name="top" id="top" placeholder="{{webpage.top_name}}" value="{{webpage.top_name}}"><br>
        name: <input type="text" name="name" id="name" value={{webpage.name}}><br>
        url: <input type="url" name="url" id="url" value="{{webpage.url}}"><br>
    <input type="submit" value="Update">
    </form>
</div>
<br>
<br>
{% endblock body_block %}

myapp/templates/form_demo.html
{% extends "index.html" %}

{% block title %}
    <title> Check topic</title>
{% endblock %}


{% block body_block %}
<div class="container">
    <div class="jumbotron">      
    <h5 align="center">
        Select a topic name to Display Details of the Topic. <br>
    </h5> 
    </div>
    
    <h1 align="center">Select the Topic</h1>
    <table align="center">
        {% if topics %}
        <form method="POST">
            {% csrf_token %}
           <tr> <td> 
            <select name="top" id="top">
            <!-- <select name="top" id="top" multiple> -->
            {% for topic in  topics %}
            <option value="{{topic}}">{{topic.top_name}}</option>              
            {% endfor %}          
         
            </select> 
            <input class="btn btn-primary" type="submit" value="submit">
        </td> </tr>
    </form>
</table>
    {% else %}
        <h1>Data not found</h1>
    {% endif %}



</div>
<br>
<br>
{% endblock body_block %}

myapp/templates/form_demo2.html
{% extends "index.html" %}

{% block title %}
    <title> Check topic</title>
{% endblock %}


{% block body_block %}
<div class="container">
    <div class="jumbotron">      
    <h5 align="center">
        Check a topic name to Display Details of the Topic. <br>
        If you want you can coose multiple topic.
    </h5> 
    </div>
    <h1 align="center">Choose the Topic</h1>
    <table align="center">
    {% if topics %}
    <form method="POST">
        {% csrf_token %}
        {% for topic in topics  %}
          
       <tr> 
        <td><label for="top">{{topic.top_name}}</label></td>
        <td><input type="checkbox" name="top" id="top" value="{{topic}}"></td> 
      </tr>
       {% endfor %}

    <tr> </tr></tr>
    <tr><td><input class="btn btn-primary" type="submit" value="submit"></td> </tr></tr>
</form>
</table>
{% else %}
    <h1>Data not found</h1>
{% endif %}
</div>
<br>
<br>
{% endblock body_block %}

myapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
    <title>Model | Index Page</title>
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <!-- <STYLE>a{text-decoration: none;} </STYLE> -->
    
</head>
<body>
    <!-- <h1 align="center" style="color:#11283e" style="font-family:inherit">PURULIA</h1> -->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #00002E;">
        <a class="navbar-brand" href="#">
          <h3> <a href="{% url 'myapp:index' %}">Model </a></h3>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <!-- <div class="collapse navbar-collapse"> -->
              <!-- <ul class="nav-item"> -->
              <li><a class="nav-link active" href="{% url 'myapp:display' %}">Display all</a></li>
              <li><a class="nav-link" href="{% url 'myapp:display_asc' %}">Asc data</a></li>
              <li><a class="nav-link" href="{% url 'myapp:display_specific' %}">Specific Data</a></li>
              <li><a class="nav-link" href="{% url 'myapp:filter_data' %}">Filter data</a></li>
              <li><a class="nav-link" href="{% url 'myapp:like_data' %}">Like Data</a></li> 
              <li><a class="nav-link" href="{% url 'myapp:topic_form' %}">Form in dropdown</a></li> 
              <li><a class="nav-link" href="{% url 'myapp:topic_form2' %}">Form in Checkbox</a></li> 
            <!-- </ul> -->
            <!-- </div> -->
          </div>
        </div>
      </nav>

      <!-- second nav  -->

      <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #00002E;">
        <a class="navbar-brand" href="#">
          <h3> <a href="{% url 'myapp:index' %}"> </a></h3>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <!-- <div class="collapse navbar-collapse"> -->
              <!-- <ul class="nav-item"> -->
              <li><a class="nav-link" href="{% url 'myapp:create_topic' %}">Add Topic</a></li>
              <li><a class="nav-link" href="{% url 'myapp:delete_topic' %}">Delete Topic</a></li>
              <li><a class="nav-link" href="{% url 'myapp:create_webpage' %}">Add Webpage</a></li>
              <li><a class="nav-link" href="{% url 'myapp:create_access_details' %}">Add Access Details</a></li>
              <li><a class="nav-link" href="{% url 'myapp:select_webpage' %}">Edit Webpage</a></li>
              <li><a class="nav-link" href="#">Edit Access Details</a></li>
               
            <!-- </ul> -->
            <!-- </div> -->
          </div>
        </div>
      </nav>


      <!-- end second nav  -->
    {% block body_block %}
        <div class="container">
            <div class="jumbotron">
                <h5 align="center">
                    Index Page <br>
                    This project is for displaying data from database in different form.
                </h5>
            </div>
        </div>
    {% endblock body_block %}
</body>
</html>

myapp/templates/like_data.html
{% extends "index.html" %}

{% block title %}
    <title> Like Data</title>
{% endblock %}

{% block body_block %}
<div class="container">
  <div class="jumbotron">      
  <h5 align="center">
      Startswith , Endswith and Contains examples are available in this page. (LIKE operater)
  </h5>
  </div>
  </div>
  {% endblock body_block %}

myapp/templates/select_webpage_for_update.html
{% extends "index.html" %}

{% block title %}
    <title> Select Webpage</title>
{% endblock %}


{% block body_block %}
<div class="container">
    <div class="jumbotron">      
    <h2 align="center">
        Select WebPage for update <br>
    </h2> 
    </div>
    <form action="{% url 'myapp:edit_webpage' %}" method="POST" >
        {% csrf_token %}
        <h1>Select a record for updation</h1>
        {% if webpages %}
        <select name="name" id="name">
            {% for webpage in webpages %}
            <option value="{{webpage}}">{{webpage.name}}</option>
            {% endfor %}
        </select>
        {% else %}
          <h1>No record</h1>
        {% endif %}
        <input type="submit" value="Submit">
    </form>
</div>
<br>
<br>
{% endblock body_block %}

myapp/templates/webpage_details.html
{% extends "index.html" %}

{% block title %}
    <title> Check topic</title>
{% endblock %}


{% block body_block %}
<div class="container">
    <div class="jumbotron">      
    <h2 align="center">
        WebPage Details According to Topic <br>
    </h2> 
    <a class="btn btn-primary" href="{% url 'myapp:topic_form' %}">Choose Topics</a>
    </div>
    {% if webpages %}
    <table class="table table-striped" border="2pt">
        <thead class="thead-dark">
        <tr>
            <th>Topic</th>
            <th>Webpage name</th>
            <th>Webpage Url</th>
        </tr>
    </thead>
        {% for webpage in webpages %}
        <tr> 
            <td>{{webpage.top_name}}</td>
            <td>{{webpage.name}}</td>
            <td>{{webpage.url}}</td>
        </tr>
        {% endfor %} 
    </table>
      
    {% else %}
      <h1>Data not found</h1>
    {% endif %}
</div>
<br>
<br>
{% endblock body_block %}













<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Webpage Details | from dropdown </title>
</head>
<body>
   
    <a href="{% url 'myapp:topic_form' %}">Choose Topics</a> 
    
</body>
</html>

myapp/templates/webpage_details2.html
{% extends "index.html" %}

{% block title %}
    <title> Check topic</title>
{% endblock %}


{% block body_block %}
<div class="container">
    <div class="jumbotron">      
    <h2 align="center">
        WebPage Details According to Topic <br>
    </h2> 
    <a class="btn btn-primary" href="{% url 'myapp:topic_form2' %}">Choose Topics</a>
    </div>
    {% if webpages %}
    <table border="2pt" class="table table-striped">
        <thead class="thead-dark">
        <tr>
            <th>Topic</th>
            <th>Webpage name</th>
            <th>Webpage Url</th>
        </tr>
    </thead>
        {% for webpage in webpages %}
        <tr> 
            <td>{{webpage.top_name}}</td>
            <td>{{webpage.name}}</td>
            <td>{{webpage.url}}</td>
        </tr>
        {% endfor %} 
    </table>
     
      
    {% else %}
      <h1>Data not found</h1>
    {% endif %}

</div>
<br>
<br>
{% endblock body_block %}